<?php

use App\Models\Backend\Menu;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class SeedMenuTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('menus', function (Blueprint $table) {
            \Illuminate\Support\Facades\DB::table('menus')->truncate();
            $data = [
                [
                    'menu_id' => null,
                    'name' => 'Institute',
                    'uri' => '/',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 1,
                    'name' => 'About Institute',
                    'uri' => '/',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Introduction',
                    'uri' => 'introduction',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Governing Body',
                    'uri' => 'governing-body',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 2,
                    'name' => 'Founder & Donor',
                    'uri' => 'founder-n-donor',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 1,
                    'name' => 'Administrative Message',
                    'uri' => '/',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 6,
                    'name' => 'President Message',
                    'uri' => 'president',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 6,
                    'name' => 'Principal Message',
                    'uri' => 'principal',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 1,
                    'name' => 'Infrastructure',
                    'uri' => '/',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 9,
                    'name' => 'Building & Rooms',
                    'uri' => 'building-room',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 9,
                    'name' => 'Library',
                    'uri' => 'library',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 9,
                    'name' => 'Transport',
                    'uri' => 'transport',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 9,
                    'name' => 'Hostel',
                    'uri' => 'hostel',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 9,
                    'name' => 'Land Information',
                    'uri' => 'land-information',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 1,
                    'name' => 'Academics',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Class Routine',
                    'uri' => 'class-routine',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Academic Calendar',
                    'uri' => 'calendar',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Syllabus',
                    'uri' => 'syllabus',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Dairy',
                    'uri' => 'diary',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Performance',
                    'uri' => 'performance',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 15,
                    'name' => 'Annual Holiday List',
                    'uri' => 'holiday',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 1,
                    'name' => 'Digital Campus',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 22,
                    'name' => 'Multimedia Class Room',
                    'uri' => 'multimedia-classroom',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 22,
                    'name' => 'Computer Lab',
                    'uri' => 'computer-lab',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 22,
                    'name' => 'Science Lab',
                    'uri' => 'science-lab',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Team',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Managing Committee',
                    'uri' => 'managing-committee',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Teachers',
                    'uri' => 'teacher',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Staff',
                    'uri' => 'staff',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Women Abuse Prevention Committee',
                    'uri' => 'wapc',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Teacher & Employee Welfare Trust',
                    'uri' => 'tswt',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 26,
                    'name' => 'Teachers Council Information',
                    'uri' => 'tci',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Result',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 33,
                    'name' => 'Internal Result',
                    'uri' => 'internal-exam',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 33,
                    'name' => 'Public Examination',
                    'uri' => 'public-exam',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 33,
                    'name' => 'Online Admission',
                    'uri' => 'online-admission',
                    'type' => 3,
                    'page_id' => 1,
                    'system_page' => 'apply-school',
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Information',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'Sports & Cultural Program',
                    'uri' => 'sports-n-culture-program',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'Center Information',
                    'uri' => 'center-information',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'Scholarship Info',
                    'uri' => 'scholarship-info',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'BNCC',
                    'uri' => 'bncc',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 4,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'Rover Scout',
                    'uri' => 'scout',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 5,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 37,
                    'name' => 'Tender',
                    'uri' => 'tender',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Attendance',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 6,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 44,
                    'name' => 'Summery',
                    'uri' => 'attendance-summery',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 44,
                    'name' => 'Student',
                    'uri' => 'student-attendance',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 44,
                    'name' => 'Teacher & Employee',
                    'uri' => 'teacher-attendance',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 3,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'News & Notice',
                    'uri' => '/',
                    'type' => 4,
                    'order' => 7,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 48,
                    'name' => 'Notice',
                    'uri' => 'notice',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 1,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => 48,
                    'name' => 'News',
                    'uri' => 'news',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 2,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Gallery',
                    'uri' => 'gallery',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 8,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Download',
                    'uri' => 'download',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 9,
                    'editable' => 0,
                    'deletable' => 0,
                ],
                [
                    'menu_id' => null,
                    'name' => 'Contacts',
                    'uri' => 'contacts',
                    'type' => 1,
                    'is_active' => 1,
                    'order' => 10,
                    'editable' => 0,
                    'deletable' => 0,
                ],
            ];

            foreach($data as $d){
                Menu::query()->create($d);
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('menus', function (Blueprint $table) {
            //
        });
    }
}
