<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class SeedPermission extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $permissionGroup = [
            [
                'group_name' => 'subscriber',
                'permissions' => [
                    "subscriber.list",
                ],
            ],
            [
                'group_name' => 'transactions',
                'permissions' => [
                    "transactions.index",
                    "transaction.create",
                    "transaction.store",
                ],
            ],
            [
                'group_name' => 'communication',
                'permissions' =>  [
                    "communication.quick",
                    "communication.student",
                    "communication.staff",
                    "communication.history",
                    "communication.send",
                    "communication.quickSend",
                    "communication.apiSetting",
                ]  ,
            ],
            [
                'group_name' => 'Student',
                'permissions' => [
                    "student.tod",
                    "student.esif",
                    "student.images",
                    "student.applied-student",
                    "student.list",
                    "student.add",
                    "student.edit",
                    "student.update",
                    "student.dropOut",
                    "student.subjects",
                    "student.assignSubject",
                    "student.promotion",
                    "student.promote",
                    "student.designStudentCard",
                    "student.testimonial",
                    "student.transport",
                    "student.downloadBlank",
                    "student.uploadStudent",
                    "assign.transport.end",
                    "storeAssignTransport",
                    "student.up",
                    "student.store",
                    "student.optional",
                    "student.assignOptional",
                    "student.pdf",
                    "student.resetPassword",
                    "student.indAttendance",
                    "student.classAttendance",
                    "student.classAttendance",
                    "student.applied-student.view",
                    "subject.student",
                    "admin.student.profile",
                    "csv",
                ],
            ],

            [
                'group_name' => 'Coa',
                'permissions' => [
                    "coa.name",
                    "coa.create",
                    "coa.store",
                    "coa.edit",
                    "coa.update",
                    "coa.destroy",
                    "coa.isEnabled",
                ],
            ],
            [
                'group_name' => 'Admission',
                'permissions' => [
                    "admission.store",
                    "admission.unapprove",
                    "admission.exams",
                    "admission.examResult",
                    "admission.browseMeritList",
                    "admission.uploadMeritList",
                    "admission.upload",
                    "admission.slipView",
                    "online-admission.index",
                    "online-admission.applyStudentProfile",
                    "online-admission.getApplyInfo",
                    "online-admission.getApplyInfoSession",
                    "online.onlineApplyIndex",
                    "online.typeSave",
                    "onlineStepEdit",
                    "online.typeUpdate",
                    "online.moveToStudent",
                ],
            ],
            [
                'group_name' => 'Event',
                'permissions' => [
                    "event.index",
                    "event.create",
                    "event.store",
                    "event.show",
                    "event.edit",
                    "event.update",
                    "event.destroy",
                ],
            ],
            [
                'group_name' => 'Playlist',
                'permissions' => [
                    "playlist.index",
                    "playlist.store",
                    "playlist.show",
                    "playlist.destroy",
                ],
            ],
            [
                'group_name' => 'Video',
                'permissions' => [
                    "video.index",
                    "video.store",
                    "video.edit",
                    "video.update",
                    "video.destroy",
                ],
            ],
            [
                'group_name' => 'Holiday Calendar',
                'permissions' => [
                    "attendance.holiday",
                    "holiday.store",
                    "holiday.edit",
                    "holiday.update",
                    "holiday.destroy",
                ],
            ],
            [
                'group_name' => 'Journals',
                'permissions' => [
                    "journals.index",
                    "journals.create",
                    "journals.store",
                    "journals.show",
                    "journals.edit",
                    "journals.update",
                    "journals.destroy",
                    "journal.classic",
                    "journal.cashBook",
                    "journal.cashBookSetting",
                    "journal.ledger",
                    "journal.trialBalance",
                    "journal.profitNLoss",
                    "journal.balanceSheet",
                ],
            ],
            [
                'group_name' => 'Menu',
                'permissions' => [
                    "menu.index",
                    "menus.search",
                    "menu.store",
                    "menu.edit",
                    "menu.update",
                    "menu.destroy",
                ],
            ],
            [
                'group_name' => '',
                'permissions' => [
                    "page.index",
                    "page.create",
                    "page.store",
                    "page.edit",
                    "page.update",
                    "page.destroy",
                    "page.remove",
                ],
            ],
            [
                'group_name' => 'Siteinfo',
                'permissions' => [
                    "siteinfo",
                    "site-info.update",
                    "site-info.update_google_map",
                    "site-info.logo",
                ],
            ],
            [
                'group_name' => 'Slider',
                'permissions' => [
                    "slider.index",
                    "slider.store",
                    "slider.destroy",
                ],
            ],
            [
                'group_name' => 'Setting Basic',
                'permissions' => [
                    "setting.index",
                    "setting.store",
                    "setting.destroy",
                    "settings.basicInfo",
                    "apiSetting.update",
                    "setting.email",
                    "email.store",
                    "email.edit",
                    "email.update",
                    "email.delete",
                    "setting.map",
                    "map.store",
                    "social.index",
                    "social.store",
                ],
            ],
            [
                'group_name' => 'Features',
                'permissions' => [
                    "features.index",
                    "features.create",
                    "features.store",
                    "features.edit",
                    "features.update",
                    "features.destroy",
                ],
            ],
            [
                'group_name' => 'Notice',
                'permissions' => [
                    "notice.index",
                    "notice.store",
                    "notice.edit",
                    "notice.update",
                    "notice.destroy",
                    "notice-category.index",
                    "notice-category.store",
                    "notice-category.edit",
                    "notice-type.index",
                    "notice-type.store",
                    "notice-type.edit",
                ],
            ],
            [
                'group_name' => 'WeeklyOff',
                'permissions' => [
                    "weeklyOff.index",
                    "weeklyOff.store",
                    "weeklyOff.edit",
                    "weeklyOff.destroy",
                ],
            ],
            [
                'group_name' => 'User',
                'permissions' => [
                    "user.index",
                    "user.add",
                    "user.store",
                    "user.edit",
                    "user.destroy",
                    "user.profile",
                    "user.update",
                    "user.password",
                ],
            ],
            [
                'group_name' => 'Syllabus',
                'permissions' => [
                    "syllabus.index",
                    "syllabus.store",
                    "syllabus.delete",
                ],
            ],
            [
                'group_name' => 'leave Purpose',
                'permissions' => [
                    "leavePurpose.index",
                    "leavePurpose.add",
                    "leavePurpose.store",
                    "leavePurpose.edit",
                    "leavePurpose.update",
                    "leavePurpose.delete",
                ],
            ],
            [
                'group_name' => 'leave Management',
                'permissions' => [
                    "leaveManagement.index",
                    "leaveManagement.create",
                    "leaveManagement.store",
                    "leaveManagement.edit",
                    "leaveManagement.destroy",
                ],
            ],
            [
                'group_name' => 'book Category',
                'permissions' => [
                    "bookCategory.index",
                    "bookCategory.add",
                    "bookCategory.store",
                    "book-category.edit",
                    "bookCategory.update",
                    "bookCategory.delete",
                    "allBooks.index",
                    "allBooks.show",
                    "allBooks.search",
                    "newBook.add",
                    "newBook.store",
                    "newBook.edit",
                    "newBook.update",
                    "newBook.delete",
                    "issueBook.index",
                    "issueBook.store",
                    "returnBook.index",
                    "returnBook.store",
                    'report'
                ],
            ],
            [
                'group_name' => 'shift',
                'permissions' => [
                    "shift.index",
                    "shift.store",
                    "shift.edit",
                    "shift.update",
                    "shift.destroy",
                ],
            ],
            [
                'group_name' => 'Exam Marks',
                'permissions' => [
                    "exam-marks.index",
                    "exam-marks.download",
                    "exam-marks.upload",
                    "exam-marks.up",
                    "exam-marks.store",
                ],
            ],
            [
                'group_name' => 'staff',
                'permissions' => [
                    "staff.staff",
                    "staff.staffPdf",
                    "staff.profile",
                    "staff.teacher",
                    "staff.create",
                    "staff.store_staff",
                    "staff.edit_staff",
                    "staff.update_staff",
                    "staff.delete_staff",
                    "staff.threshold",
                    "staff.kpi",
                    "staff.payslip",
                ],
            ],
            [
                'group_name' => 'Message',
                'permissions' => [
                    "message.index",
                    "message.destroy",
                    "message.view",
                    "message.store",
                    "chairmanMessage.index",
                    "principalMessage.index",
                    "aboutInstitute.index",
                    "instituteMessageUpdate",
                ],
            ],
            [
                'group_name' => 'class schedule',
                'permissions' => [
                    "class.schedule.index",
                    "class.schedule.store",
                    "class.schedule.update",
                    "class.schedule.delete",
                ],
            ],
            [
                'group_name' => 'Tuition Fee',
                'permissions' => [
                    "fee-setup.create",
                    "fee-setup.store",
                    "fee-setup.index",
                    "fee-setup.feeStudents",
                    "fee-setup.feeSetupDetails",
                    "fee-setup.search",
                    "fee-setup.edit",
                    "fee-setup.editByStudent",
                    "fee-setup.updateByStudent",
                    "fee.fee-setup.update",
                    "fee.fee-setup.delete",
                    "fee-cart.store",
                    "fee-cart.destroy",
                    "fee-cart.flush",
                    "fee.EditFeeCartDestroy",
                    "fee-collection.index",
                    "fee-collection.view",
                    "fee-collection.store",
                    "fee-collection.allCollections",
                    "fee-collection.report",
                    "report.generate",
                    "report.academic_class",
                    "pdf.classReport",
                    "pdf.dateWiseReport",
                    "fee-category.index",
                    "fee_categories.search",
                    "fee-category.store",
                    "fee-category.edit",
                    "fee-category.update",
                    "fee-category.delete",
                    "fee-category.status",
                    "fee-setup.fee_setup",
                    "fee-setup.list",
                    "fee-setup.show",
                    "fee-setup.update",
                ],
            ],

            [
                'group_name' => 'gallery',
                'permissions' => [
                    "settings.image",
                    "gallery.store",
                    "gallery.destroy",
                    "gallery-category.index",
                    "gallery-category.store",
                    "gallery-category.destroy",
                    "gallery-albums.index",
                    "gallery-albums.store",
                    "gallery-albums.destroy",
                    "galleryCorner.create",
                    "GalleryCornerStore",
                    "GalleryImage.destroy",
                ],
            ],
            [
                'group_name' => 'Academic Calender',
                'permissions' => [
                    "academic-calender.index",
                    "academic-calender.store",
                    "academic-calender.edit",
                    "academic-calender.update",
                    "academic-calender.delete",
                    "academic-calender.status",
                ],
            ],
            [
                'group_name' => 'Transport',
                'permissions' => [
                    "transport.index",
                    "transport.store",
                    "transport.edit",
                    "transport.update",
                    "transport.student-list",
                    "transport.assign",
                ],
            ],
            [
                'group_name' => 'diary',
                'permissions' => [
                    "diary.index",
                    "diary.create",
                    "diary.store",
                    "diary.edit",
                    "diary.update",
                ],
            ],
            [
                'group_name' => '',
                'permissions' => [
                    "institution.academicyear",
                    "institution.store_session",
                    "institution.edit_session",
                    "institution.update_session",
                    "institution.delete_session",
                    "institution.sessionStatus",
                    "institution.unAssignSubject",
                    "section.group",
                    "institution.create_section",
                    "institution.edit_section",
                    "institution.update_section",
                    "institution.delete_section",
                    "institution.create_group",
                    "institution.edit_group",
                    "institution.update_group",
                    "institution.delete_grp",
                    "institution.classes",
                    "institution.store_class",
                    "institution.academicClasses",
                    "institution.storeAcademicClass",
                    "institution.editAcademicClass",
                    "institution.updateAcademicClass",
                    "institution.edit_SessionClass",
                    "institution.update_SessionClass",
                    "institution.delete_SessionClass",
                    "institution.classSubjects",
                    "institution.class.subject.unAssignSubject",
                    "institution.subjects",
                    "institution.create_subject",
                    "institution.edit_subject",
                    "institution.update_subject",
                    "institution.delete_subject",
                    "assign.subject",
                    "edit.assign",
                    "institution.delete_assigned",
                    "institution.profileinstitution.profile",
                    "institution.signature",
                    "institution.sig",
                ],
            ],
            [
                'group_name' => 'Report',
                'permissions' => [
                    "report.student-fee",
                    "report.student-monthly-fee",
                ],
            ],
            [
                'group_name' => 'attendance',
                'permissions' => [
                    "custom.view",
                    "attendance.dashboard",
                    "attendance.student",
                    "attendance.teacher",
                    "attendance.report",
                    "attendance.getAttendanceMonthly",
                    "student.indAttendance",
                    "student.classAttendance",
                    "teacher.indAttendance",
                    "TeacherLeaveManagement.index"
                ],
            ],
            [
                'group_name' => 'Exam',
                'permissions' => [
                    "exam.gradesystem",
                    "exam.store_grade",
                    "exam.delete_grade",
                    "exam.examination",
                    "store.exam",
                    "exam.destroy",
                    "exam.examitems",
                    "exam.schedule.create",
                    "exam.schedule.store",
                    "exam.schedule.index",
                    "exam.store_schedule",
                    "exam.admitCard",
                    "exam.seatAllocate",
                    "exam-seat-plan.seatPlan",
                    "exam-seat-plan.CheckRoll",
                    "exam-seat-plan.storeSeatPlan",
                    "exam-seat-plan.pdfSeatPlan",
                    "exam-seat-plan.destroy",
                    "exam.resultDetails",
                    "exam.finalResultDetails",
                    "exam.allDetails",
                    "exam.examresult",
                    "exam.tabulation",
                    "exam.generateResult",
                    "exam.setfinalresultrule",
                    "exam.getfinalresultrule",
                    "exam.finalResultNew",
                ],
            ],[
                'group_name' => 'Role',
                'permissions' => [
                    "role.index",
                    "role.create",
                    "role.store",
                    "role.edit",
                    "role.update",
                ],
            ],
            [
                'group_name' => 'theme',
                'permissions' => [
                    "theme.index",
                    "theme.edit",
                    "theme.destroy",
                ],
            ],
            [
                'group_name' => 'db-backup',
                'permissions' => [
                    "backup.db",
                    "backup.download",
                    "backup.create",
                ],
            ],

        ];

        foreach ($permissionGroup as $p){
            $gpName = $p['group_name'];
            foreach ($p['permissions'] as $permission){
                \App\Models\Backend\Permission::create([
                    'group_name' => $gpName,
                    'name' => $permission,
                    'module_id' => 1,
                ]);
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
